copy_src() {
	ibex_root_path=$1
	out_dir=$2
	# Build ibex using fusesoc
	fusesoc --cores-root $ibex_root_path run --tool=icarus --target=lint --setup "lowrisc:ibex:ibex_simple_system" > /dev/null 2>&1
	# Copy autogenerated source files to $out_dir/src
	mkdir -p $out_dir/src
	cp build/*/src/*/*.sv  build/*/src/*/*/*.sv  $out_dir/src
	cp build/*/src/*/*.svh build/*/src/*/*/*.svh $out_dir/src
	# remove tracer (not needed for synthesis)
	rm -f $out_dir/src/ibex_tracer.sv
	rm -f $out_dir/src/ibex_top_tracing.sv
	rm -f $out_dir/src/timer.sv
}

sv2v_convert() {
	out_dir=$1
	mkdir -p $out_dir/generated

	# Convert core sources
	for file in $out_dir/src/*.sv; do
		module=`basename -s .sv $file`

		# Skip packages
		if echo "$module" | grep -q '_pkg$'; then
			continue
		fi

		# Convert SystemVerilog files to Verilog using sv2v
		sv2v \
		--define=SYNTHESIS --define=YOSYS \
		$out_dir/src/*_pkg.sv \
		$file \
		> $out_dir/generated/${module}.v
	done

	# Remove unsupported $value$plusargs keyword
	sed -i 's+$value$plusargs+// +g' $out_dir/generated/prim_generic_ram_1p.v
	sed -i 's+$value$plusargs+// +g' $out_dir/generated/prim_generic_ram_2p.v
}

"$@"
